version: '3.8'

x-airflow-common: &airflow-common
  build: .
  environment: &airflow-common-env
    PYTHONPATH: /opt/airflow:/opt/airflow/src
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_main:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW_CONN_POSTGRES_MAIN: 'postgres://airflow:airflow@postgres_main:5432/airflow'
    AIRFLOW_CONN_MINIO_CONN: 'aws://minioadmin:minioadmin@?endpoint_url=http%3A%2F%2Fminio%3A9000'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - revolut_network

services:
  postgres_main:
    image: postgres:15-alpine
    container_name: postgres_main
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_silver.sql:/docker-entrypoint-initdb.d/init_silver.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5
    networks:
      - revolut_network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 3G
    restart: always
    depends_on:
      postgres_main:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      clickhouse-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    restart: always
    depends_on:
      postgres_main:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      clickhouse-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        /entrypoint airflow db migrate
        airflow users create --username airflow --password airflow --firstname Admin --lastname Admin --role Admin --email admin@example.com || true
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
    user: "0:0"

  # МИНИО (Хранилище)
  minio:
    image: minio/minio:RELEASE.2024-01-11T07-46-16Z
    container_name: minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - revolut_network

  # CLICKHOUSE (Аналитика)
  clickhouse:
    image: clickhouse/clickhouse-server:23.12-alpine
    container_name: clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=''
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - revolut_network
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  clickhouse-init:
    image: clickhouse/clickhouse-server:23.12-alpine
    container_name: clickhouse_init
    depends_on:
      clickhouse:
        condition: service_healthy
    volumes:
      - ./scripts/init_gold.sql:/init/init_gold.sql
    networks:
      - revolut_network
    entrypoint: >
      /bin/sh -c "
      echo 'Running DDL scripts...';
      clickhouse-client --host clickhouse --multiquery < /init/init_gold.sql;
      echo 'DDL applied successfully.';
      "
  
  # metabase:
  #   image: metabase/metabase:latest
  #   container_name: metabase
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     MB_DB_TYPE: h2
  #   volumes:
  #     - ./metabase-data:/metabase-data
  #   restart: always

volumes:
  postgres_data:
  minio_data:
  clickhouse_data:

networks:
  revolut_network:
    driver: bridge
