x-airflow-common: &airflow-common
  build: .
  environment: &airflow-common-env
    PYTHONPATH: /opt/airflow:/opt/airflow/src
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_main:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    AIRFLOW_PYTHONPATH: /opt/airflow/src:/opt/airflow/dags
    AIRFLOW_CONN_POSTGRES_MAIN: 'postgres://airflow:airflow@postgres_main:5432/airflow'
    AIRFLOW_CONN_MINIO_CONN: 'aws://minioadmin:minioadmin@?endpoint_url=http%3A%2F%2Fminio%3A9000'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./.git:opt/airflow/.git:ro
    - ./src:/opt/airflow/src
    - ./sql:/opt/airflow/sql
    - ./logs:/opt/airflow/logs
    # - ./plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - revolut_network

services:
  api:
    build: .
    entrypoint: python
    command: -m uvicorn revolut_app.api_service.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /opt/airflow/src
      POSTGRES_HOST: postgres_main
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
      CLICKHOUSE_DATABASE: gold
    volumes:
      - ./src:/opt/airflow/src
      - ./.git:/opt/airflow/.git:ro
      - ./data:/opt/airflow/data
    depends_on:
      postgres_main:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    networks:
      - revolut_network
    profiles:
      - api

  postgres_main:
    image: postgres:15
    container_name: postgres_main
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      retries: 5
    networks:
      - revolut_network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 3G
    restart: always
    depends_on:
      postgres_main:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: scheduler
    restart: always
    depends_on:
      postgres_main:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        /entrypoint airflow db migrate
        airflow users create --username airflow --password airflow --firstname Admin --lastname Admin --role Admin --email admin@example.com || true
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
    user: "0:0"

  minio:
    image: minio/minio:RELEASE.2024-01-11T07-46-16Z
    container_name: minio
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - revolut_network

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=gold
    volumes:
      - ./sql/clickhouse/init_gold.sql:/docker-entrypoint-initdb.d/init_gold.sql
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    depends_on:
      - postgres_main
    networks:
      - revolut_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  metabase:
    image: metabase/metabase:v0.62.1
    container_name: metabase
    ports:
      - "3001:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_PLUGINS_DIR: /plugins
    volumes:
      - metabase_data:/metabase-data
      - ./metabase/plugins:/plugins
    depends_on:
      postgres_main:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: always
    networks:
      - revolut_network

volumes:
  postgres_data:
  minio_data:
  clickhouse_data:
  metabase_data:

networks:
  revolut_network:
    driver: bridge
