DEFAULT_POSITION_LIMIT = 100_000.0
ZERO_FLOAT = 0.0
ONE_FLOAT = 1.0
ZERO_INT = 0
ONE_INT = 1
DEFAULT_HEDGE_CAPACITY = 50_000.0
DEFAULT_FUNDING_COST_BPS = 1.0
DEFAULT_MARKET_VOLATILITY = 0.01
DEFAULT_ORDER_FLOW_EWMA = 0.0

DEFAULT_CURRENCY_STATES = {
    'EUR': {
        'position': 10_000.0,
        'position_limit': 100_000.0,
        'hedge_capacity': 50_000.0,
        'max_hedge_capacity': 50_000.0,
        'funding_cost_bps': 1.2,
        'market_volatility': 0.012,
    },
    'GBP': {
        'position': 8_000.0,
        'position_limit': 90_000.0,
        'hedge_capacity': 40_000.0,
        'max_hedge_capacity': 40_000.0,
        'funding_cost_bps': 1.4,
        'market_volatility': 0.014,
    },
    'USD': {
        'position': 15_000.0,
        'position_limit': 120_000.0,
        'hedge_capacity': 60_000.0,
        'max_hedge_capacity': 60_000.0,
        'funding_cost_bps': 1.0,
        'market_volatility': 0.01,
    },
}

USD_MARKS = {
    'USD': 1.00,
    'EUR': 1.08,
    'GBP': 1.27,
}

AMOUNT_PRECISION = 4
BPS_DENOMINATOR = 10_000.0
MID_RATE_PRECISION = 6
CLIENT_RATE_PRECISION = 6
COMPONENT_BPS_PRECISION = 4
POSITION_PRECISION = 6
STATE_VALUE_PRECISION = 4
RATIO_PRECISION = 6

PREMIUM_BASE_SPREAD_BPS = 2.0
BUSINESS_BASE_SPREAD_BPS = 4.0
RETAIL_BASE_SPREAD_BPS = 6.0

BASE_INVENTORY_PENALTY_WEIGHT_BPS = 18.0
QUOTE_INVENTORY_PENALTY_WEIGHT_BPS = 8.0
LIQUIDITY_PRESSURE_THRESHOLD = 0.55
LIQUIDITY_PENALTY_WEIGHT_BPS = 10.0

POSITION_PRESSURE_WEIGHT = 0.65
ORDER_FLOW_PRESSURE_WEIGHT = 0.25
LIQUIDITY_PRESSURE_WEIGHT = 0.10
MIN_PRESSURE = -2.0
MAX_PRESSURE = 2.0
ORDER_FLOW_NORMALIZER = 10_000.0
ORDER_FLOW_DECAY = 0.92
EPSILON = 1e-12

DEFAULT_STRESS_VOLATILITY_MULTIPLIER = 2.0
DEFAULT_STRESS_HEDGE_CAPACITY_MULTIPLIER = 0.7

STRESS_PRESSURE_THRESHOLD = 0.9
STRESS_VOLATILITY_THRESHOLD = 0.045
STRESS_LIMIT_UTILIZATION_THRESHOLD = 0.9
ELEVATED_PRESSURE_THRESHOLD = 0.6
ELEVATED_VOLATILITY_THRESHOLD = 0.025
ELEVATED_LIMIT_UTILIZATION_THRESHOLD = 0.7
CALM_REGIME_PENALTY_BPS = 0.0
ELEVATED_REGIME_PENALTY_BPS = 4.0
STRESS_REGIME_PENALTY_BPS = 12.0

DEFAULT_HAWKES_STEPS = 1_000
DEFAULT_HAWKES_DT_SECONDS = 10
DEFAULT_HAWKES_BASE_INTENSITY = 0.015
DEFAULT_HAWKES_ALPHA = 0.08
DEFAULT_HAWKES_BETA = 0.12
HAWKES_BUY_PROBABILITY = 0.55
HAWKES_LOGNORMAL_MEAN = 0.7
HAWKES_LOGNORMAL_SIGMA = 0.75
PREMIUM_SEGMENT_PROBABILITY = 0.12
BUSINESS_SEGMENT_PROBABILITY = 0.20
SECONDS_PER_MINUTE = 60.0

MIN_ACCEPTANCE_PROBABILITY = 0.03
MAX_ACCEPTANCE_PROBABILITY = 0.995
ACCEPTANCE_SPREAD_NORMALIZER_BPS = 100.0
LARGE_AMOUNT_THRESHOLD = 100_000.0
MEDIUM_AMOUNT_THRESHOLD = 50_000.0
LARGE_AMOUNT_ACCEPTANCE_MULTIPLIER = 0.8
MEDIUM_AMOUNT_ACCEPTANCE_MULTIPLIER = 0.9
DEFAULT_AMOUNT_ACCEPTANCE_MULTIPLIER = 1.0
ELEVATED_ACCEPTANCE_MULTIPLIER = 0.85
STRESS_ACCEPTANCE_MULTIPLIER = 0.7
DEFAULT_REGIME_ACCEPTANCE_MULTIPLIER = 1.0
PREMIUM_SEGMENT_SENSITIVITY = 0.65
BUSINESS_SEGMENT_SENSITIVITY = 0.8
RETAIL_SEGMENT_SENSITIVITY = 1.0

DEFAULT_SIMULATION_STEPS = 5_000
DEFAULT_SIMULATION_BASE_INTENSITY = 0.03
DEFAULT_SIMULATION_SEED = 42
DEFAULT_AMOUNT_MULTIPLIER = 1_000.0
DEFAULT_MAX_SNAPSHOTS = 100
MIN_SIMULATION_STEPS = 1
MAX_SIMULATION_STEPS = 100_000
MIN_DT_SECONDS = 1
MAX_DT_SECONDS = 3_600
MIN_INTENSITY = 0.0
MAX_INTENSITY = 1.0
MIN_ALPHA = 0.0
MAX_ALPHA = 5.0
MIN_BETA = 0.0
MAX_BETA = 10.0
MIN_AMOUNT_MULTIPLIER = 0.0
MAX_AMOUNT_MULTIPLIER = 1_000_000.0
MIN_MAX_SNAPSHOTS = 0
MAX_MAX_SNAPSHOTS = 10_000

DEFAULT_RG_STRESS_THRESHOLD = 0.8
DEFAULT_RG_WINDOW_SIZES = [1, 5, 20, 100]
MIN_RG_WINDOW_SIZE = 1

DEFAULT_HEDGE_PRESSURE_THRESHOLD = 0.75
DEFAULT_HEDGE_TARGET_PRESSURE = 0.35
DEFAULT_MAX_HEDGE_FRACTION = 0.5
DEFAULT_MIN_HEDGE_NOTIONAL = 1_000.0
STRESS_HEDGE_PRESSURE_THRESHOLD = 0.55
ELEVATED_HEDGE_PRESSURE_THRESHOLD = 0.65
MIN_HEDGE_PRESSURE_THRESHOLD = 0.0
MAX_HEDGE_PRESSURE_THRESHOLD = 2.0
MIN_HEDGE_TARGET_PRESSURE = 0.0
MAX_HEDGE_TARGET_PRESSURE = 2.0
MIN_MAX_HEDGE_FRACTION = 0.0
MAX_MAX_HEDGE_FRACTION = 1.0
MIN_HEDGE_NOTIONAL = 0.0

PNL_PRECISION = 6
DEFAULT_PNL_FUNDING_COST_USD = 0.0
DEFAULT_PNL_LAST_EVENTS_LIMIT = 10

NAIVE_FIXED_SPREAD_BPS = 6.0

PLATFORM_PREMIUM_BASE_SPREAD_BPS = 0.5
PLATFORM_BUSINESS_BASE_SPREAD_BPS = 2.0
PLATFORM_RETAIL_BASE_SPREAD_BPS = 4.0

PLATFORM_INVENTORY_PENALTY_MULTIPLIER = 0.85
PLATFORM_LIQUIDITY_PENALTY_MULTIPLIER = 0.85
PLATFORM_REGIME_PENALTY_MULTIPLIER = 0.75

PLATFORM_RETAIL_REVENUE_PER_ACCEPTED_EVENT_USD = 0.05
PLATFORM_PREMIUM_REVENUE_PER_ACCEPTED_EVENT_USD = 0.40
PLATFORM_BUSINESS_REVENUE_PER_ACCEPTED_EVENT_USD = 0.75

MIN_POLICY_COMPARISON_POLICIES = 2
DEFAULT_POLICY_COMPARISON_AMOUNT_MULTIPLIER = 500.0
DEFAULT_POLICY_SNAPSHOT_EVERY_N_EVENTS = 10
MIN_POLICY_SNAPSHOT_EVERY_N_EVENTS = 1
MAX_POLICY_SNAPSHOT_EVERY_N_EVENTS = 10_000
