DEFAULT_HEDGE_COST_BPS = 2.0
MIN_HEDGE_COST_BPS = 0.0
MAX_HEDGE_COST_BPS = 100.0

DEFAULT_MAX_HEDGE_ACTIONS = 10
MIN_HEDGE_ACTIONS = 1
MAX_HEDGE_ACTIONS = 50

EXECUTION_AMOUNT_PRECISION = 6
EXECUTION_COST_PRECISION = 6
